//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataColumn
    {
        public long ID { get; set; }
        public string DC_Code { get; set; }
        public string DC_Name { get; set; }
        public Nullable<long> DC_MID { get; set; }
        public string DC_Order { get; set; }
        public Nullable<long> DEnable { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
